steps:
- name: "gcr.io/cloud-builders/kubectl"
  args: ['get', 'nodes']
  env:
  - 'CLOUDSDK_COMPUTE_REGION=us-central1'
  - 'CLOUDSDK_CONTAINER_CLUSTER=private-cluster'
options:
  workerPool:
    'projects/cluster-build/locations/us-central1/workerPools/build-pool'