steps:
- name: "gcr.io/cloud-builders/kubectl"
  args: ['create', 'deployment', 'pubuilc-nx', '--image','nginx']
  env:
  - 'CLOUDSDK_COMPUTE_REGION=us-central1'
  - 'CLOUDSDK_CONTAINER_CLUSTER=public-cluster'
#options:
#  workerPool:
#    'projects/cluster-build/locations/us-central1/workerPools/build-pool'